version: '3'

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      MYSQL_DATABASE: some_db
      MYSQL_USER: some_db_user
      MYSQL_PASSWORD: some_db_password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  php56:
    image: ermustaqbal/php56:latest
    restart: always
    container_name: php56
    depends_on:
      - db
    volumes:
      - ./php:/var/www/odeta
    ports:
      - "80:80"
